### ISSUE TITLE
Using the raw data

### ISSUE THREAD

**Issue by pixeldesbois** [DFRobot/DFRobot_TCS3430#1]
Hello,
How to convert raw data into "true" values ​​based on gain and time values ?

In my tests (same condition) I have with TCS3430.setIntegrationTime(0x0) : 
TCS3430.setALSGain(3)   return  X : 838  Y : 836  Z : 276
TCS3430.setALSGain(2)   return  X : 203  Y : 205  Z : 67
TCS3430.setALSGain(1)   return  X : 51  Y : 52  Z : 17

Thank in advance
Stéphane

**Comment by fary99** [comment]
Sorry, this library only provides basic driver methods
